<?php 
include_once("fonctions_systeme.php");
include_once("fonctions_initialisation.php"); 
include_once("fonctions_chaine.php"); 
include_once("fonctions_data.php"); 
include_once("fonctions_date.php"); 
include_once("fonctions_verif.php");
include_once("fonctions_debug.php");
?>